// app/projects.tsx
import { DateRange, List } from "@/app/common";
import { PrimarySection, SecondarySection } from "@/app/sections";
import type { ProjectData, ProjectsData } from "@/app/types";

export default function Projects({ projects }: { projects: ProjectsData }) {
  return (
    <PrimarySection title="Projects">
      {projects.map((project, index) => (
        <Project key={index} {...project} />
      ))}
    </PrimarySection>
  );
}

function Project({ name, url, startDate, endDate, highlights }: ProjectData) {
  return (
    <SecondarySection
      title={name}
      url={url}
      subtitle={<DateRange startDate={startDate} endDate={endDate} />}
    >
      <List items={highlights} />
    </SecondarySection>
  );
}

// src/routes/projects.svelte
<script lang="ts">
	import DateRange from '$lib/components/date-range.svelte';
	import List from '$lib/components/list.svelte';
	import SecondarySection from '$lib/components/secondary-section.svelte';
	import PrimarySection from '$lib/components/primary-section.svelte';
	import type { ProjectExperience } from '$lib/types';

	interface Props {
		projects: ProjectExperience[];
	}

	const { projects }: Props = $props();
</script>

<PrimarySection title="Projects">
	{#each projects as project (project)}
		<SecondarySection title={project.name} url={project.url}>
			{#snippet subtitle()}
				<p><DateRange start={project.start_date} end={project.end_date} /></p>
			{/snippet}

			<List items={project.highlights} />
		</SecondarySection>
	{/each}
</PrimarySection>
