// src/routes/work.svelte
<script lang="ts">
	import List from '$lib/components/list.svelte';
	import Location from '$lib/components/location.svelte';
	import PrimarySection from '$lib/components/primary-section.svelte';
	import SecondarySection from '$lib/components/secondary-section.svelte';
	import TertiarySection from '$lib/components/tertiary-section.svelte';
	import type { WorkExperience } from '$lib/types';

	interface Props {
		work: WorkExperience[];
	}

	const { work }: Props = $props();
</script>

<PrimarySection title="Work Experience">
	{#each work as experience (experience)}
		<SecondarySection title={experience.company} url={experience.url}>
			{#snippet subtitle()}
				<Location location={experience.location} />
			{/snippet}

			{#each experience.positions as position (position)}
				<TertiarySection
					title={position.title}
					start_date={position.start_date}
					end_date={position.end_date}
				>
					<List items={position.highlights} />
				</TertiarySection>
			{/each}
		</SecondarySection>
	{/each}
</PrimarySection>

// app/work.tsx
import { List } from "@/app/common";
import { PrimarySection, SecondarySection, TertiarySection } from "@/app/sections";
import type { WorkData, WorkOrganizationData, WorkPositionData } from "@/app/types";

export default function Work({ work }: { work: WorkData }) {
  return (
    <PrimarySection title="Work Experience">
      {work.map((organization, index) => (
        <WorkOrganization key={index} {...organization} />
      ))}
    </PrimarySection>
  );
}

function WorkOrganization({ location, organization, positions, url }: WorkOrganizationData) {
  return (
    <SecondarySection title={organization} url={url} subtitle={<p>{location}</p>}>
      {positions.map((position, index) => (
        <WorkPosition key={index} {...position} />
      ))}
    </SecondarySection>
  );
}

function WorkPosition({ endDate, highlights, position, startDate }: WorkPositionData) {
  return (
    <TertiarySection title={position} startDate={startDate} endDate={endDate}>
      {highlights && <List items={highlights} />}
    </TertiarySection>
  );
}
