// app/education.tsx
import { List, sublist } from "@/app/common";
import { PrimarySection, SecondarySection, TertiarySection } from "@/app/sections";
import type { EducationData, EducationInstitutionData } from "@/app/types";

export default function Education({ education }: { education: EducationData }) {
  return (
    <PrimarySection title="Education">
      {education.map((institution, index) => (
        <EducationInstitution key={index} {...institution} />
      ))}
    </PrimarySection>
  );
}

function EducationInstitution(props: EducationInstitutionData) {
  return (
    <SecondarySection title={props.institution} url={props.url} subtitle={<p>{props.location}</p>}>
      <TertiarySection
        title={`${props.studyType} in ${props.area}`}
        startDate={props.startDate}
        endDate={props.endDate}
      >
        <List
          items={[
            sublist("Honors", props.honors),
            sublist("Courses", props.courses),
            ...(props.highlights ?? []),
          ]}
        />
      </TertiarySection>
    </SecondarySection>
  );
}

// src/routes/(home)/education.svelte
<script lang="ts" module>
	import List from '$lib/components/list.svelte';
	import Location from '$lib/components/location.svelte';
	import PrimarySection from '$lib/components/primary-section.svelte';
	import SecondarySection from '$lib/components/secondary-section.svelte';
	import TertiarySection from '$lib/components/tertiary-section.svelte';
	import type { EducationExperience } from '$lib/types';
</script>

<script lang="ts">
	interface Props {
		education: EducationExperience[];
	}

	const { education }: Props = $props();
</script>

<PrimarySection title="Education">
	{#each education as experience (experience)}
		<SecondarySection title={experience.institution} url={experience.url}>
			{#snippet subtitle()}
				<Location location={experience.location} />
			{/snippet}

			<TertiarySection
				title="{experience.degree} in {experience.major}"
				subtitle={null}
				start_date={experience.start_date}
				end_date={experience.end_date}
			>
				<List
					items={[
						['Honors', experience.honors],
						['Courses', experience.courses],
						...experience.highlights
					]}
				/>
			</TertiarySection>
		</SecondarySection>
	{/each}
</PrimarySection>
